Using data in the repo: /lustre/storeB/users/paulinast/repos/github/bias_correction_of_storm_surge_model_with_nn/ml_storm_surge_operational/data_loader/preprocessor_operational_predict.py

Conda env: mlstormsurge (had to reinstall xarray as it wasn't in the env)

In [1]:
import numpy as np
import datetime as dt
import pytz

In [2]:
from ml_storm_surge_operational.data_loader.prepare_df_operational_prod import PrepareDataFrames

In [3]:
from ml_storm_surge_operational.data_loader.preprocessor_operational_predict import (
    PreprocessInput 
    as PreprocessInputPredict
)

In [4]:
datetime_predict = '2025-05-19 00:00'
datetime_predict = (
        dt.datetime
        .strptime(datetime_predict, "%Y-%m-%d %H:%M")
        .replace(tzinfo=pytz.UTC)
    )
datetime_predict

datetime.datetime(2025, 5, 19, 0, 0, tzinfo=<UTC>)

In [5]:
feature_vars = [
    'obs', 
    'tide_py', 
    'stormsurge_corrected', 
    'u10', 
    'v10'
    ] 

label_var = 'stormsurge_corrected - (obs - tide_py)'

window_width_past = [24, 24, 0, 0, 0]
window_width_future = [-1, 60, 60, 60, 60]  # -1 does not include time t0
horizon = 60  

datetime_start_hourly = datetime_predict

In [6]:
5*4*60 + 5*2*24

1440

In [7]:
station = 'NO_OSC'
feature_stations = ['NO_OSC', 'NO_AES', 'NO_BGO', 'NO_VIK', 'NO_TRG']

In [8]:
pp = PreprocessInputPredict(
    feature_vars = feature_vars,
    label_var = label_var,
    window_width_past = window_width_past,
    window_width_future = window_width_future,
    horizon = horizon,
    feature_stations = feature_stations,
    label_station = station,
    datetime_start_hourly = datetime_start_hourly,
    datetime_end_hourly = datetime_start_hourly,
    remove_nans = False,
    normalize=True,
    use_existing_files=False,
    past_forecast=24
    )
pp.preprocess_data()

Call PrepareDataFrames...
Preparing feature and label df...
Preparing auxiliary DataFrame...
Generating obs and tide_py DataFrame form operational data for the past...
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 0 start:  0 end:  144 var: observed_at_chartdatum
[0.36999997 0.30999997 0.30999997 0.34999996 0.39999998 0.40999997
 0.45999998 0.53999996 0.59       0.57       0.51       0.43999997
 0.37999997 0.32       0.29       0.29999998 0.33999997 0.35999998
 0.37999997 0.43999997 0.51       0.53999996 0.53       0.48999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 1 start:  6 end:  150 var: observed_at_chartdatum
[0.30999997 0.30999997 0.34999996 0.39999998 0.40999997 0.45999998
 0.53999996 0.59       0.57       0.51       0.43999997 0.37999997
 0.32       0.29       0.29999998 0.33999997 0.35999998 0.37999997
 0.43999997 0.51       0.53999996 0.53       0.48999998 0.42999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 2 start:  12 end:  156 var: observed_at_chartdatum
[0.30999997 0.34999996 0.39999998 0.40999997 0.45999998 0.53999996
 0.59       0.57       0.51       0.43999997 0.37999997 0.32
 0.29       0.29999998 0.33999997 0.35999998 0.37999997 0.43999997
 0.51       0.53999996 0.53       0.48999998 0.42999998 0.35999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 3 start:  18 end:  162 var: observed_at_chartdatum
[0.34999996 0.39999998 0.40999997 0.45999998 0.53999996 0.59
 0.57       0.51       0.43999997 0.37999997 0.32       0.29
 0.29999998 0.33999997 0.35999998 0.37999997 0.43999997 0.51
 0.53999996 0.53       0.48999998 0.42999998 0.35999998 0.30999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 4 start:  24 end:  168 var: observed_at_chartdatum
[0.39999998 0.40999997 0.45999998 0.53999996 0.59       0.57
 0.51       0.43999997 0.37999997 0.32       0.29       0.29999998
 0.33999997 0.35999998 0.37999997 0.43999997 0.51       0.53999996
 0.53       0.48999998 0.42999998 0.35999998 0.30999997 0.32      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 5 start:  30 end:  174 var: observed_at_chartdatum
[0.40999997 0.45999998 0.53999996 0.59       0.57       0.51
 0.43999997 0.37999997 0.32       0.29       0.29999998 0.33999997
 0.35999998 0.37999997 0.43999997 0.51       0.53999996 0.53
 0.48999998 0.42999998 0.35999998 0.30999997 0.32       0.34999996]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 6 start:  36 end:  180 var: observed_at_chartdatum
[0.45999998 0.53999996 0.59       0.57       0.51       0.43999997
 0.37999997 0.32       0.29       0.29999998 0.33999997 0.35999998
 0.37999997 0.43999997 0.51       0.53999996 0.53       0.48999998
 0.42999998 0.35999998 0.30999997 0.32       0.34999996 0.35999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 7 start:  42 end:  186 var: observed_at_chartdatum
[0.53999996 0.59       0.57       0.51       0.43999997 0.37999997
 0.32       0.29       0.29999998 0.33999997 0.35999998 0.37999997
 0.43999997 0.51       0.53999996 0.53       0.48999998 0.42999998
 0.35999998 0.30999997 0.32       0.34999996 0.35999998 0.39      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 8 start:  48 end:  192 var: observed_at_chartdatum
[0.59       0.57       0.51       0.43999997 0.37999997 0.32
 0.29       0.29999998 0.33999997 0.35999998 0.37999997 0.43999997
 0.51       0.53999996 0.53       0.48999998 0.42999998 0.35999998
 0.30999997 0.32       0.34999996 0.35999998 0.39       0.46999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 9 start:  54 end:  198 var: observed_at_chartdatum
[0.57       0.51       0.43999997 0.37999997 0.32       0.29
 0.29999998 0.33999997 0.35999998 0.37999997 0.43999997 0.51
 0.53999996 0.53       0.48999998 0.42999998 0.35999998 0.30999997
 0.32       0.34999996 0.35999998 0.39       0.46999997 0.56      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 10 start:  60 end:  204 var: observed_at_chartdatum
[0.51       0.43999997 0.37999997 0.32       0.29       0.29999998
 0.33999997 0.35999998 0.37999997 0.43999997 0.51       0.53999996
 0.53       0.48999998 0.42999998 0.35999998 0.30999997 0.32
 0.34999996 0.35999998 0.39       0.46999997 0.56       0.59      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 11 start:  66 end:  210 var: observed_at_chartdatum
[0.43999997 0.37999997 0.32       0.29       0.29999998 0.33999997
 0.35999998 0.37999997 0.43999997 0.51       0.53999996 0.53
 0.48999998 0.42999998 0.35999998 0.30999997 0.32       0.34999996
 0.35999998 0.39       0.46999997 0.56       0.59       0.57      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 0 start:  0 end:  144 var: observed_at_chartdatum
[0.37999997 0.32       0.29       0.29999998 0.33999997 0.35999998
 0.37999997 0.43999997 0.51       0.53999996 0.53       0.48999998
 0.42999998 0.35999998 0.30999997 0.32       0.34999996 0.35999998
 0.39       0.46999997 0.56       0.59       0.57       0.52      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 1 start:  6 end:  150 var: observed_at_chartdatum
[0.32       0.29       0.29999998 0.33999997 0.35999998 0.37999997
 0.43999997 0.51       0.53999996 0.53       0.48999998 0.42999998
 0.35999998 0.30999997 0.32       0.34999996 0.35999998 0.39
 0.46999997 0.56       0.59       0.57       0.52       0.45      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 2 start:  12 end:  156 var: observed_at_chartdatum
[0.29       0.29999998 0.33999997 0.35999998 0.37999997 0.43999997
 0.51       0.53999996 0.53       0.48999998 0.42999998 0.35999998
 0.30999997 0.32       0.34999996 0.35999998 0.39       0.46999997
 0.56       0.59       0.57       0.52       0.45       0.34999996]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 3 start:  18 end:  162 var: observed_at_chartdatum
[0.29999998 0.33999997 0.35999998 0.37999997 0.43999997 0.51
 0.53999996 0.53       0.48999998 0.42999998 0.35999998 0.30999997
 0.32       0.34999996 0.35999998 0.39       0.46999997 0.56
 0.59       0.57       0.52       0.45       0.34999996 0.26999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 4 start:  24 end:  168 var: observed_at_chartdatum
[0.33999997 0.35999998 0.37999997 0.43999997 0.51       0.53999996
 0.53       0.48999998 0.42999998 0.35999998 0.30999997 0.32
 0.34999996 0.35999998 0.39       0.46999997 0.56       0.59
 0.57       0.52       0.45       0.34999996 0.26999998 0.22999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 5 start:  30 end:  174 var: observed_at_chartdatum
[0.35999998 0.37999997 0.43999997 0.51       0.53999996 0.53
 0.48999998 0.42999998 0.35999998 0.30999997 0.32       0.34999996
 0.35999998 0.39       0.46999997 0.56       0.59       0.57
 0.52       0.45       0.34999996 0.26999998 0.22999997 0.23999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 6 start:  36 end:  180 var: observed_at_chartdatum
[0.37999997 0.43999997 0.51       0.53999996 0.53       0.48999998
 0.42999998 0.35999998 0.30999997 0.32       0.34999996 0.35999998
 0.39       0.46999997 0.56       0.59       0.57       0.52
 0.45       0.34999996 0.26999998 0.22999997 0.23999998 0.27999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 7 start:  42 end:  186 var: observed_at_chartdatum
[0.43999997 0.51       0.53999996 0.53       0.48999998 0.42999998
 0.35999998 0.30999997 0.32       0.34999996 0.35999998 0.39
 0.46999997 0.56       0.59       0.57       0.52       0.45
 0.34999996 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 8 start:  48 end:  192 var: observed_at_chartdatum
[0.51       0.53999996 0.53       0.48999998 0.42999998 0.35999998
 0.30999997 0.32       0.34999996 0.35999998 0.39       0.46999997
 0.56       0.59       0.57       0.52       0.45       0.34999996
 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 9 start:  54 end:  198 var: observed_at_chartdatum
[0.53999996 0.53       0.48999998 0.42999998 0.35999998 0.30999997
 0.32       0.34999996 0.35999998 0.39       0.46999997 0.56
 0.59       0.57       0.52       0.45       0.34999996 0.26999998
 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 10 start:  60 end:  204 var: observed_at_chartdatum
[0.53       0.48999998 0.42999998 0.35999998 0.30999997 0.32
 0.34999996 0.35999998 0.39       0.46999997 0.56       0.59
 0.57       0.52       0.45       0.34999996 0.26999998 0.22999997
 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997 0.58      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 11 start:  66 end:  210 var: observed_at_chartdatum
[0.48999998 0.42999998 0.35999998 0.30999997 0.32       0.34999996
 0.35999998 0.39       0.46999997 0.56       0.59       0.57
 0.52       0.45       0.34999996 0.26999998 0.22999997 0.23999998
 0.27999997 0.32999998 0.39999998 0.49999997 0.58       0.59999996]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 0 start:  0 end:  144 var: observed_at_chartdatum
[0.42999998 0.35999998 0.30999997 0.32       0.34999996 0.35999998
 0.39       0.46999997 0.56       0.59       0.57       0.52
 0.45       0.34999996 0.26999998 0.22999997 0.23999998 0.27999997
 0.32999998 0.39999998 0.49999997 0.58       0.59999996 0.57      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 1 start:  6 end:  150 var: observed_at_chartdatum
[0.35999998 0.30999997 0.32       0.34999996 0.35999998 0.39
 0.46999997 0.56       0.59       0.57       0.52       0.45
 0.34999996 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998
 0.39999998 0.49999997 0.58       0.59999996 0.57       0.49999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 2 start:  12 end:  156 var: observed_at_chartdatum
[0.30999997 0.32       0.34999996 0.35999998 0.39       0.46999997
 0.56       0.59       0.57       0.52       0.45       0.34999996
 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998
 0.49999997 0.58       0.59999996 0.57       0.49999997 0.39      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 3 start:  18 end:  162 var: observed_at_chartdatum
[0.32       0.34999996 0.35999998 0.39       0.46999997 0.56
 0.59       0.57       0.52       0.45       0.34999996 0.26999998
 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997
 0.58       0.59999996 0.57       0.49999997 0.39       0.29999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 4 start:  24 end:  168 var: observed_at_chartdatum
[0.34999996 0.35999998 0.39       0.46999997 0.56       0.59
 0.57       0.52       0.45       0.34999996 0.26999998 0.22999997
 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997 0.58
 0.59999996 0.57       0.49999997 0.39       0.29999998 0.26      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 5 start:  30 end:  174 var: observed_at_chartdatum
[0.35999998 0.39       0.46999997 0.56       0.59       0.57
 0.52       0.45       0.34999996 0.26999998 0.22999997 0.23999998
 0.27999997 0.32999998 0.39999998 0.49999997 0.58       0.59999996
 0.57       0.49999997 0.39       0.29999998 0.26       0.29      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 6 start:  36 end:  180 var: observed_at_chartdatum
[0.39       0.46999997 0.56       0.59       0.57       0.52
 0.45       0.34999996 0.26999998 0.22999997 0.23999998 0.27999997
 0.32999998 0.39999998 0.49999997 0.58       0.59999996 0.57
 0.49999997 0.39       0.29999998 0.26       0.29       0.33999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 7 start:  42 end:  186 var: observed_at_chartdatum
[0.46999997 0.56       0.59       0.57       0.52       0.45
 0.34999996 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998
 0.39999998 0.49999997 0.58       0.59999996 0.57       0.49999997
 0.39       0.29999998 0.26       0.29       0.33999997 0.36999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 8 start:  48 end:  192 var: observed_at_chartdatum
[0.56       0.59       0.57       0.52       0.45       0.34999996
 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998
 0.49999997 0.58       0.59999996 0.57       0.49999997 0.39
 0.29999998 0.26       0.29       0.33999997 0.36999997 0.42      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 9 start:  54 end:  198 var: observed_at_chartdatum
[0.59       0.57       0.52       0.45       0.34999996 0.26999998
 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997
 0.58       0.59999996 0.57       0.49999997 0.39       0.29999998
 0.26       0.29       0.33999997 0.36999997 0.42       0.52      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 10 start:  60 end:  204 var: observed_at_chartdatum
[0.57       0.52       0.45       0.34999996 0.26999998 0.22999997
 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997 0.58
 0.59999996 0.57       0.49999997 0.39       0.29999998 0.26
 0.29       0.33999997 0.36999997 0.42       0.52       0.59999996]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 11 start:  66 end:  210 var: observed_at_chartdatum
[0.52       0.45       0.34999996 0.26999998 0.22999997 0.23999998
 0.27999997 0.32999998 0.39999998 0.49999997 0.58       0.59999996
 0.57       0.49999997 0.39       0.29999998 0.26       0.29
 0.33999997 0.36999997 0.42       0.52       0.59999996 0.60999995]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 0 start:  0 end:  144 var: tide_at_chartdatum
[0.62 0.57 0.57 0.59 0.62 0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54
 0.51 0.53 0.55 0.57 0.59 0.65 0.72 0.75 0.74 0.7 ]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 1 start:  6 end:  150 var: tide_at_chartdatum
[0.57 0.57 0.59 0.62 0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51
 0.53 0.55 0.57 0.59 0.65 0.72 0.75 0.74 0.7  0.65]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 2 start:  12 end:  156 var: tide_at_chartdatum
[0.57 0.59 0.62 0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53
 0.55 0.57 0.59 0.65 0.72 0.75 0.74 0.7  0.65 0.59]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 3 start:  18 end:  162 var: tide_at_chartdatum
[0.59 0.62 0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55
 0.57 0.59 0.65 0.72 0.75 0.74 0.7  0.65 0.59 0.54]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 4 start:  24 end:  168 var: tide_at_chartdatum
[0.62 0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57
 0.59 0.65 0.72 0.75 0.74 0.7  0.65 0.59 0.54 0.54]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 5 start:  30 end:  174 var: tide_at_chartdatum
[0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59
 0.65 0.72 0.75 0.74 0.7  0.65 0.59 0.54 0.54 0.57]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 6 start:  36 end:  180 var: tide_at_chartdatum
[0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59 0.65
 0.72 0.75 0.74 0.7  0.65 0.59 0.54 0.54 0.57 0.6 ]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 7 start:  42 end:  186 var: tide_at_chartdatum
[0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59 0.65 0.72
 0.75 0.74 0.7  0.65 0.59 0.54 0.54 0.57 0.6  0.62]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 8 start:  48 end:  192 var: tide_at_chartdatum
[0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59 0.65 0.72 0.75
 0.74 0.7  0.65 0.59 0.54 0.54 0.57 0.6  0.62 0.67]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 9 start:  54 end:  198 var: tide_at_chartdatum
[0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59 0.65 0.72 0.75 0.74
 0.7  0.65 0.59 0.54 0.54 0.57 0.6  0.62 0.67 0.73]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 10 start:  60 end:  204 var: tide_at_chartdatum

In [9]:
b = pp.x_y_dict
b

{'x': array([[0.36999997, 0.30999997, 0.30999997, ..., 0.78485978, 0.57452244,
         0.56918639]]),
 'y': array([[ 0.06024949,  0.0705893 ,  0.07542259,  0.07242292,  0.07640114,
          0.09304567,  0.07050721,  0.01899135, -0.03752959, -0.06187911,
         -0.06741655, -0.07077298, -0.06347105, -0.01902017,  0.01756594,
          0.04111029,  0.05920464,  0.05235945,  0.02312016,  0.00433026,
         -0.0230546 , -0.03019145, -0.0179874 , -0.00899222,  0.00445132,
          0.04332313,  0.0502204 ,  0.02838716, -0.0007408 , -0.02558455,
         -0.01641762, -0.03536725, -0.07487251, -0.08540973, -0.06636079,
         -0.03650905, -0.03365451, -0.02706811,  0.00366706,  0.02821173,
          0.05497056,  0.05186011,  0.02634732,  0.00716382, -0.02810299,
         -0.07112163, -0.1011367 , -0.11536658, -0.12172854, -0.11754116,
         -0.09991813, -0.07932043, -0.10714349, -0.13509199, -0.16334733,
         -0.161623  , -0.18873322, -0.23189139, -0.23008564, -0.18348977]]),
 'x_train_mean': array([ 0.65750347,  0.67193263,  0.67943607, ..., -0.43044824,
        -0.34699575, -0.35558755]),
 'x_train_std': array([0.25376401, 0.25322089, 0.25244463, ..., 4.16689705, 4.1419366 ,
        4.21874288]),
 'y_train_mean': array([ 0.00400644,  0.00754638,  0.00859077,  0.0091238 ,  0.00904603,
         0.00616365,  0.00213811,  0.00121413,  0.00322614,  0.00359077,
         0.00159958,  0.00097894,  0.00379305,  0.00799615,  0.00981197,
         0.01068295,  0.0099333 ,  0.00640283,  0.00174714,  0.00029215,
         0.00199381,  0.00299464,  0.00196456,  0.00247121,  0.00536117,
         0.00996323,  0.01146426,  0.01158403,  0.01024149,  0.00575898,
         0.00041599, -0.00178803,  0.00042081,  0.00184222,  0.00151778,
         0.00263385,  0.00628474,  0.0101931 ,  0.01171423,  0.01182878,
         0.01059856,  0.00569982,  0.0004289 , -0.00093635,  0.00131725,
         0.00150009,  0.00017964,  0.00172815,  0.00562448,  0.00918502,
         0.00984097,  0.0109101 ,  0.01141328,  0.00687942,  0.00152417,
        -0.00074875,  0.00019415, -0.00037735, -0.00188068, -0.00102306]),
 'y_train_std': array([0.06473953, 0.06329717, 0.06431861, 0.06545488, 0.06394294,
        0.06300335, 0.06332278, 0.06435365, 0.06556784, 0.06659836,
        0.0689148 , 0.07029244, 0.07006284, 0.06960003, 0.07077824,
        0.07114487, 0.06969956, 0.06910864, 0.06934548, 0.07072344,
        0.07262803, 0.07364236, 0.07481881, 0.07558917, 0.0745617 ,
        0.07367699, 0.07430445, 0.07422594, 0.07429909, 0.07435107,
        0.07356319, 0.07491583, 0.07814913, 0.07888867, 0.07923402,
        0.07968742, 0.0788877 , 0.07813236, 0.07806128, 0.07768892,
        0.07800586, 0.07737175, 0.07578977, 0.07757389, 0.08023515,
        0.08126686, 0.08137973, 0.08220064, 0.08230489, 0.08162971,
        0.08092756, 0.08033096, 0.08064111, 0.08038165, 0.07835994,
        0.08127805, 0.08511039, 0.08636548, 0.08632707, 0.08821845]),
 'x_norm': array([[-1.13295611, -1.42931595, -1.46343413, ...,  0.2916578 ,
          0.22248486,  0.21920605]]),
 'y_norm': array([[ 0.868759  ,  0.99598336,  1.03907436,  0.96706491,  1.05336282,
          1.37900639,  1.07969206,  0.27624261, -0.62158105, -0.98305546,
         -1.00147028, -1.02076289, -0.96005395, -0.38816533,  0.10955294,
          0.42768147,  0.70691029,  0.66499084,  0.30821086,  0.05709726,
         -0.34488625, -0.45063862, -0.26667033, -0.15165452, -0.01220259,
          0.45278581,  0.52158576,  0.22637817, -0.14781181, -0.42156118,
         -0.22883195, -0.44822589, -0.96345689, -1.10601365, -0.8566847 ,
         -0.49120556, -0.50627979, -0.47689848, -0.10308796,  0.21087886,
          0.56882911,  0.59660392,  0.34197793,  0.10441875, -0.36667529,
         -0.89362036, -1.24498252, -1.42449896, -1.54733236, -1.55245165,
         -1.35626352, -1.12323487, -1.47017786, -1.76621657, -2.10402803,
         -1.97930754, -2.21979207, -2.68063177, -2.64349266, -2.06835093]])}

In [10]:
# TODO: Get 67 lead times. Otherwise, we cannot use pre-generated y_train_mean and std, and the same for x.

In [11]:
pp.y

array([[ 0.06024949,  0.0705893 ,  0.07542259,  0.07242292,  0.07640114,
         0.09304567,  0.07050721,  0.01899135, -0.03752959, -0.06187911,
        -0.06741655, -0.07077298, -0.06347105, -0.01902017,  0.01756594,
         0.04111029,  0.05920464,  0.05235945,  0.02312016,  0.00433026,
        -0.0230546 , -0.03019145, -0.0179874 , -0.00899222,  0.00445132,
         0.04332313,  0.0502204 ,  0.02838716, -0.0007408 , -0.02558455,
        -0.01641762, -0.03536725, -0.07487251, -0.08540973, -0.06636079,
        -0.03650905, -0.03365451, -0.02706811,  0.00366706,  0.02821173,
         0.05497056,  0.05186011,  0.02634732,  0.00716382, -0.02810299,
        -0.07112163, -0.1011367 , -0.11536658, -0.12172854, -0.11754116,
        -0.09991813, -0.07932043, -0.10714349, -0.13509199, -0.16334733,
        -0.161623  , -0.18873322, -0.23189139, -0.23008564, -0.18348977]])

In [12]:
prep = PrepareDataFrames(
    variables=feature_vars + [label_var],
    stations=feature_stations + [station],
    horizon=horizon + 1,  # max
    window_width_past=24, # use the same for obs and tide
    datetime_start_hourly=datetime_start_hourly,
    datetime_end_hourly=datetime_start_hourly,
    use_existing_files=False,
    past_forecast=24
    )

prep.prepare_features_labels_df()

Preparing auxiliary DataFrame...
Generating obs and tide_py DataFrame form operational data for the past...
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 0 start:  0 end:  144 var: observed_at_chartdatum
[0.36999997 0.30999997 0.30999997 0.34999996 0.39999998 0.40999997
 0.45999998 0.53999996 0.59       0.57       0.51       0.43999997
 0.37999997 0.32       0.29       0.29999998 0.33999997 0.35999998
 0.37999997 0.43999997 0.51       0.53999996 0.53       0.48999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 1 start:  6 end:  150 var: observed_at_chartdatum
[0.30999997 0.30999997 0.34999996 0.39999998 0.40999997 0.45999998
 0.53999996 0.59       0.57       0.51       0.43999997 0.37999997
 0.32       0.29       0.29999998 0.33999997 0.35999998 0.37999997
 0.43999997 0.51       0.53999996 0.53       0.48999998 0.42999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 2 start:  12 end:  156 var: observed_at_chartdatum
[0.30999997 0.34999996 0.39999998 0.40999997 0.45999998 0.53999996
 0.59       0.57       0.51       0.43999997 0.37999997 0.32
 0.29       0.29999998 0.33999997 0.35999998 0.37999997 0.43999997
 0.51       0.53999996 0.53       0.48999998 0.42999998 0.35999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 3 start:  18 end:  162 var: observed_at_chartdatum
[0.34999996 0.39999998 0.40999997 0.45999998 0.53999996 0.59
 0.57       0.51       0.43999997 0.37999997 0.32       0.29
 0.29999998 0.33999997 0.35999998 0.37999997 0.43999997 0.51
 0.53999996 0.53       0.48999998 0.42999998 0.35999998 0.30999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 4 start:  24 end:  168 var: observed_at_chartdatum
[0.39999998 0.40999997 0.45999998 0.53999996 0.59       0.57
 0.51       0.43999997 0.37999997 0.32       0.29       0.29999998
 0.33999997 0.35999998 0.37999997 0.43999997 0.51       0.53999996
 0.53       0.48999998 0.42999998 0.35999998 0.30999997 0.32      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 5 start:  30 end:  174 var: observed_at_chartdatum
[0.40999997 0.45999998 0.53999996 0.59       0.57       0.51
 0.43999997 0.37999997 0.32       0.29       0.29999998 0.33999997
 0.35999998 0.37999997 0.43999997 0.51       0.53999996 0.53
 0.48999998 0.42999998 0.35999998 0.30999997 0.32       0.34999996]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 6 start:  36 end:  180 var: observed_at_chartdatum
[0.45999998 0.53999996 0.59       0.57       0.51       0.43999997
 0.37999997 0.32       0.29       0.29999998 0.33999997 0.35999998
 0.37999997 0.43999997 0.51       0.53999996 0.53       0.48999998
 0.42999998 0.35999998 0.30999997 0.32       0.34999996 0.35999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 7 start:  42 end:  186 var: observed_at_chartdatum
[0.53999996 0.59       0.57       0.51       0.43999997 0.37999997
 0.32       0.29       0.29999998 0.33999997 0.35999998 0.37999997
 0.43999997 0.51       0.53999996 0.53       0.48999998 0.42999998
 0.35999998 0.30999997 0.32       0.34999996 0.35999998 0.39      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 8 start:  48 end:  192 var: observed_at_chartdatum
[0.59       0.57       0.51       0.43999997 0.37999997 0.32
 0.29       0.29999998 0.33999997 0.35999998 0.37999997 0.43999997
 0.51       0.53999996 0.53       0.48999998 0.42999998 0.35999998
 0.30999997 0.32       0.34999996 0.35999998 0.39       0.46999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 9 start:  54 end:  198 var: observed_at_chartdatum
[0.57       0.51       0.43999997 0.37999997 0.32       0.29
 0.29999998 0.33999997 0.35999998 0.37999997 0.43999997 0.51
 0.53999996 0.53       0.48999998 0.42999998 0.35999998 0.30999997
 0.32       0.34999996 0.35999998 0.39       0.46999997 0.56      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 10 start:  60 end:  204 var: observed_at_chartdatum
[0.51       0.43999997 0.37999997 0.32       0.29       0.29999998
 0.33999997 0.35999998 0.37999997 0.43999997 0.51       0.53999996
 0.53       0.48999998 0.42999998 0.35999998 0.30999997 0.32
 0.34999996 0.35999998 0.39       0.46999997 0.56       0.59      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 11 start:  66 end:  210 var: observed_at_chartdatum
[0.43999997 0.37999997 0.32       0.29       0.29999998 0.33999997
 0.35999998 0.37999997 0.43999997 0.51       0.53999996 0.53
 0.48999998 0.42999998 0.35999998 0.30999997 0.32       0.34999996
 0.35999998 0.39       0.46999997 0.56       0.59       0.57      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 0 start:  0 end:  144 var: observed_at_chartdatum
[0.37999997 0.32       0.29       0.29999998 0.33999997 0.35999998
 0.37999997 0.43999997 0.51       0.53999996 0.53       0.48999998
 0.42999998 0.35999998 0.30999997 0.32       0.34999996 0.35999998
 0.39       0.46999997 0.56       0.59       0.57       0.52      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 1 start:  6 end:  150 var: observed_at_chartdatum
[0.32       0.29       0.29999998 0.33999997 0.35999998 0.37999997
 0.43999997 0.51       0.53999996 0.53       0.48999998 0.42999998
 0.35999998 0.30999997 0.32       0.34999996 0.35999998 0.39
 0.46999997 0.56       0.59       0.57       0.52       0.45      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 2 start:  12 end:  156 var: observed_at_chartdatum
[0.29       0.29999998 0.33999997 0.35999998 0.37999997 0.43999997
 0.51       0.53999996 0.53       0.48999998 0.42999998 0.35999998
 0.30999997 0.32       0.34999996 0.35999998 0.39       0.46999997
 0.56       0.59       0.57       0.52       0.45       0.34999996]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 3 start:  18 end:  162 var: observed_at_chartdatum
[0.29999998 0.33999997 0.35999998 0.37999997 0.43999997 0.51
 0.53999996 0.53       0.48999998 0.42999998 0.35999998 0.30999997
 0.32       0.34999996 0.35999998 0.39       0.46999997 0.56
 0.59       0.57       0.52       0.45       0.34999996 0.26999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 4 start:  24 end:  168 var: observed_at_chartdatum
[0.33999997 0.35999998 0.37999997 0.43999997 0.51       0.53999996
 0.53       0.48999998 0.42999998 0.35999998 0.30999997 0.32
 0.34999996 0.35999998 0.39       0.46999997 0.56       0.59
 0.57       0.52       0.45       0.34999996 0.26999998 0.22999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 5 start:  30 end:  174 var: observed_at_chartdatum
[0.35999998 0.37999997 0.43999997 0.51       0.53999996 0.53
 0.48999998 0.42999998 0.35999998 0.30999997 0.32       0.34999996
 0.35999998 0.39       0.46999997 0.56       0.59       0.57
 0.52       0.45       0.34999996 0.26999998 0.22999997 0.23999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 6 start:  36 end:  180 var: observed_at_chartdatum
[0.37999997 0.43999997 0.51       0.53999996 0.53       0.48999998
 0.42999998 0.35999998 0.30999997 0.32       0.34999996 0.35999998
 0.39       0.46999997 0.56       0.59       0.57       0.52
 0.45       0.34999996 0.26999998 0.22999997 0.23999998 0.27999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 7 start:  42 end:  186 var: observed_at_chartdatum
[0.43999997 0.51       0.53999996 0.53       0.48999998 0.42999998
 0.35999998 0.30999997 0.32       0.34999996 0.35999998 0.39
 0.46999997 0.56       0.59       0.57       0.52       0.45
 0.34999996 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 8 start:  48 end:  192 var: observed_at_chartdatum
[0.51       0.53999996 0.53       0.48999998 0.42999998 0.35999998
 0.30999997 0.32       0.34999996 0.35999998 0.39       0.46999997
 0.56       0.59       0.57       0.52       0.45       0.34999996
 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 9 start:  54 end:  198 var: observed_at_chartdatum
[0.53999996 0.53       0.48999998 0.42999998 0.35999998 0.30999997
 0.32       0.34999996 0.35999998 0.39       0.46999997 0.56
 0.59       0.57       0.52       0.45       0.34999996 0.26999998
 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 10 start:  60 end:  204 var: observed_at_chartdatum
[0.53       0.48999998 0.42999998 0.35999998 0.30999997 0.32
 0.34999996 0.35999998 0.39       0.46999997 0.56       0.59
 0.57       0.52       0.45       0.34999996 0.26999998 0.22999997
 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997 0.58      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051812
i: 1 j: 11 start:  66 end:  210 var: observed_at_chartdatum
[0.48999998 0.42999998 0.35999998 0.30999997 0.32       0.34999996
 0.35999998 0.39       0.46999997 0.56       0.59       0.57
 0.52       0.45       0.34999996 0.26999998 0.22999997 0.23999998
 0.27999997 0.32999998 0.39999998 0.49999997 0.58       0.59999996]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 0 start:  0 end:  144 var: observed_at_chartdatum
[0.42999998 0.35999998 0.30999997 0.32       0.34999996 0.35999998
 0.39       0.46999997 0.56       0.59       0.57       0.52
 0.45       0.34999996 0.26999998 0.22999997 0.23999998 0.27999997
 0.32999998 0.39999998 0.49999997 0.58       0.59999996 0.57      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 1 start:  6 end:  150 var: observed_at_chartdatum
[0.35999998 0.30999997 0.32       0.34999996 0.35999998 0.39
 0.46999997 0.56       0.59       0.57       0.52       0.45
 0.34999996 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998
 0.39999998 0.49999997 0.58       0.59999996 0.57       0.49999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 2 start:  12 end:  156 var: observed_at_chartdatum
[0.30999997 0.32       0.34999996 0.35999998 0.39       0.46999997
 0.56       0.59       0.57       0.52       0.45       0.34999996
 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998
 0.49999997 0.58       0.59999996 0.57       0.49999997 0.39      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 3 start:  18 end:  162 var: observed_at_chartdatum
[0.32       0.34999996 0.35999998 0.39       0.46999997 0.56
 0.59       0.57       0.52       0.45       0.34999996 0.26999998
 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997
 0.58       0.59999996 0.57       0.49999997 0.39       0.29999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 4 start:  24 end:  168 var: observed_at_chartdatum
[0.34999996 0.35999998 0.39       0.46999997 0.56       0.59
 0.57       0.52       0.45       0.34999996 0.26999998 0.22999997
 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997 0.58
 0.59999996 0.57       0.49999997 0.39       0.29999998 0.26      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 5 start:  30 end:  174 var: observed_at_chartdatum
[0.35999998 0.39       0.46999997 0.56       0.59       0.57
 0.52       0.45       0.34999996 0.26999998 0.22999997 0.23999998
 0.27999997 0.32999998 0.39999998 0.49999997 0.58       0.59999996
 0.57       0.49999997 0.39       0.29999998 0.26       0.29      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 6 start:  36 end:  180 var: observed_at_chartdatum
[0.39       0.46999997 0.56       0.59       0.57       0.52
 0.45       0.34999996 0.26999998 0.22999997 0.23999998 0.27999997
 0.32999998 0.39999998 0.49999997 0.58       0.59999996 0.57
 0.49999997 0.39       0.29999998 0.26       0.29       0.33999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 7 start:  42 end:  186 var: observed_at_chartdatum
[0.46999997 0.56       0.59       0.57       0.52       0.45
 0.34999996 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998
 0.39999998 0.49999997 0.58       0.59999996 0.57       0.49999997
 0.39       0.29999998 0.26       0.29       0.33999997 0.36999997]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 8 start:  48 end:  192 var: observed_at_chartdatum
[0.56       0.59       0.57       0.52       0.45       0.34999996
 0.26999998 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998
 0.49999997 0.58       0.59999996 0.57       0.49999997 0.39
 0.29999998 0.26       0.29       0.33999997 0.36999997 0.42      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 9 start:  54 end:  198 var: observed_at_chartdatum
[0.59       0.57       0.52       0.45       0.34999996 0.26999998
 0.22999997 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997
 0.58       0.59999996 0.57       0.49999997 0.39       0.29999998
 0.26       0.29       0.33999997 0.36999997 0.42       0.52      ]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 10 start:  60 end:  204 var: observed_at_chartdatum
[0.57       0.52       0.45       0.34999996 0.26999998 0.22999997
 0.23999998 0.27999997 0.32999998 0.39999998 0.49999997 0.58
 0.59999996 0.57       0.49999997 0.39       0.29999998 0.26
 0.29       0.33999997 0.36999997 0.42       0.52       0.59999996]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051900
i: 2 j: 11 start:  66 end:  210 var: observed_at_chartdatum
[0.52       0.45       0.34999996 0.26999998 0.22999997 0.23999998
 0.27999997 0.32999998 0.39999998 0.49999997 0.58       0.59999996
 0.57       0.49999997 0.39       0.29999998 0.26       0.29
 0.33999997 0.36999997 0.42       0.52       0.59999996 0.60999995]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 0 start:  0 end:  144 var: tide_at_chartdatum
[0.62 0.57 0.57 0.59 0.62 0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54
 0.51 0.53 0.55 0.57 0.59 0.65 0.72 0.75 0.74 0.7 ]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 1 start:  6 end:  150 var: tide_at_chartdatum
[0.57 0.57 0.59 0.62 0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51
 0.53 0.55 0.57 0.59 0.65 0.72 0.75 0.74 0.7  0.65]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 2 start:  12 end:  156 var: tide_at_chartdatum
[0.57 0.59 0.62 0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53
 0.55 0.57 0.59 0.65 0.72 0.75 0.74 0.7  0.65 0.59]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 3 start:  18 end:  162 var: tide_at_chartdatum
[0.59 0.62 0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55
 0.57 0.59 0.65 0.72 0.75 0.74 0.7  0.65 0.59 0.54]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 4 start:  24 end:  168 var: tide_at_chartdatum
[0.62 0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57
 0.59 0.65 0.72 0.75 0.74 0.7  0.65 0.59 0.54 0.54]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 5 start:  30 end:  174 var: tide_at_chartdatum
[0.63 0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59
 0.65 0.72 0.75 0.74 0.7  0.65 0.59 0.54 0.54 0.57]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 6 start:  36 end:  180 var: tide_at_chartdatum
[0.65 0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59 0.65
 0.72 0.75 0.74 0.7  0.65 0.59 0.54 0.54 0.57 0.6 ]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 7 start:  42 end:  186 var: tide_at_chartdatum
[0.71 0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59 0.65 0.72
 0.75 0.74 0.7  0.65 0.59 0.54 0.54 0.57 0.6  0.62]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 8 start:  48 end:  192 var: tide_at_chartdatum
[0.75 0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59 0.65 0.72 0.75
 0.74 0.7  0.65 0.59 0.54 0.54 0.57 0.6  0.62 0.67]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 9 start:  54 end:  198 var: tide_at_chartdatum
[0.75 0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59 0.65 0.72 0.75 0.74
 0.7  0.65 0.59 0.54 0.54 0.57 0.6  0.62 0.67 0.73]
var: tide_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 10 start:  60 end:  204 var: tide_at_chartdatum
[0.71 0.65 0.59 0.54 0.51 0.53 0.55 0.57 0.59 0.65 0.72 0.75 0.74 0.7

,obs_t-24_NO_BGO,obs_t-23_NO_BGO,obs_t-22_NO_BGO,obs_t-21_NO_BGO,obs_t-20_NO_BGO,obs_t-19_NO_BGO,obs_t-18_NO_BGO,obs_t-17_NO_BGO,obs_t-16_NO_BGO,obs_t-15_NO_BGO,...,stormsurge_corrected - (obs - tide_py)_t51_NO_TRG,stormsurge_corrected - (obs - tide_py)_t52_NO_TRG,stormsurge_corrected - (obs - tide_py)_t53_NO_TRG,stormsurge_corrected - (obs - tide_py)_t54_NO_TRG,stormsurge_corrected - (obs - tide_py)_t55_NO_TRG,stormsurge_corrected - (obs - tide_py)_t56_NO_TRG,stormsurge_corrected - (obs - tide_py)_t57_NO_TRG,stormsurge_corrected - (obs - tide_py)_t58_NO_TRG,stormsurge_corrected - (obs - tide_py)_t59_NO_TRG,stormsurge_corrected - (obs - tide_py)_t60_NO_TRG
2025-05-19 00:00:00+00:00,1.16,1.21,1.12,0.93,0.69,0.51,0.41,0.41,0.56,0.72,...,-0.048778,-0.058738,-0.077967,-0.088305,-0.108785,-0.119698,-0.130394,-0.131245,-0.132747,-0.123424

In [13]:
prep.df_features_and_labels[['stormsurge_corrected - (obs - tide_py)_t16_NO_OSC']]

                           stormsurge_corrected - (obs - tide_py)_t16_NO_OSC
2025-05-19 00:00:00+00:00                                           0.059205

In [14]:
prep.df_features_and_labels[['stormsurge_corrected - (obs - tide_py)_NO_OSC']]

                           stormsurge_corrected - (obs - tide_py)_NO_OSC
2025-05-19 00:00:00+00:00                                       0.060249

In [15]:
prep.df_features_and_labels[['obs_NO_OSC']]

                           obs_NO_OSC
2025-05-19 00:00:00+00:00        0.43

In [16]:
prep.df_features_and_labels[['stormsurge_corrected_NO_OSC']]

                           stormsurge_corrected_NO_OSC
2025-05-19 00:00:00+00:00                    -0.159751

In [17]:
cols = prep.df_features_and_labels.columns

In [18]:
for c in cols:
    print(c)

obs_t-24_NO_BGO
obs_t-23_NO_BGO
obs_t-22_NO_BGO
obs_t-21_NO_BGO
obs_t-20_NO_BGO
obs_t-19_NO_BGO
obs_t-18_NO_BGO
obs_t-17_NO_BGO
obs_t-16_NO_BGO
obs_t-15_NO_BGO
obs_t-14_NO_BGO
obs_t-13_NO_BGO
obs_t-12_NO_BGO
obs_t-11_NO_BGO
obs_t-10_NO_BGO
obs_t-9_NO_BGO
obs_t-8_NO_BGO
obs_t-7_NO_BGO
obs_t-6_NO_BGO
obs_t-5_NO_BGO
obs_t-4_NO_BGO
obs_t-3_NO_BGO
obs_t-2_NO_BGO
obs_t-1_NO_BGO
tide_py_t-24_NO_BGO
tide_py_t-23_NO_BGO
tide_py_t-22_NO_BGO
tide_py_t-21_NO_BGO
tide_py_t-20_NO_BGO
tide_py_t-19_NO_BGO
tide_py_t-18_NO_BGO
tide_py_t-17_NO_BGO
tide_py_t-16_NO_BGO
tide_py_t-15_NO_BGO
tide_py_t-14_NO_BGO
tide_py_t-13_NO_BGO
tide_py_t-12_NO_BGO
tide_py_t-11_NO_BGO
tide_py_t-10_NO_BGO
tide_py_t-9_NO_BGO
tide_py_t-8_NO_BGO
tide_py_t-7_NO_BGO
tide_py_t-6_NO_BGO
tide_py_t-5_NO_BGO
tide_py_t-4_NO_BGO
tide_py_t-3_NO_BGO
tide_py_t-2_NO_BGO
tide_py_t-1_NO_BGO
obs_t-24_NO_VIK
obs_t-23_NO_VIK
obs_t-22_NO_VIK
obs_t-21_NO_VIK
obs_t-20_NO_VIK
obs_t-19_NO_VIK
obs_t-18_NO_VIK
obs_t-17_NO_VIK
obs_t-16_NO_VIK
obs_t-15_NO_VIK
obs_t-14_NO_VIK
obs_t-13_NO_VIK
obs_t-12_NO_VIK
obs_t-11_NO_VIK
obs_t-10_NO_VIK
obs_t-9_NO_VIK
obs_t-8_NO_VIK
obs_t-7_NO_VIK
obs_t-6_NO_VIK
obs_t-5_NO_VIK
obs_t-4_NO_VIK
obs_t-3_NO_VIK
obs_t-2_NO_VIK
obs_t-1_NO_VIK
tide_py_t-24_NO_VIK
tide_py_t-23_NO_VIK
tide_py_t-22_NO_VIK
tide_py_t-21_NO_VIK
tide_py_t-20_NO_VIK
tide_py_t-19_NO_VIK
tide_py_t-18_NO_VIK
tide_py_t-17_NO_VIK
tide_py_t-16_NO_VIK
tide_py_t-15_NO_VIK
tide_py_t-14_NO_VIK
tide_py_t-13_NO_VIK
tide_py_t-12_NO_VIK
tide_py_t-11_NO_VIK
tide_py_t-10_NO_VIK
tide_py_t-9_NO_VIK
tide_py_t-8_NO_VIK
tide_py_t-7_NO_VIK
tide_py_t-6_NO_VIK
tide_py_t-5_NO_VIK
tide_py_t-4_NO_VIK
tide_py_t-3_NO_VIK
tide_py_t-2_NO_VIK
tide_py_t-1_NO_VIK
obs_t-24_NO_OSC
obs_t-23_NO_OSC
obs_t-22_NO_OSC
obs_t-21_NO_OSC
obs_t-20_NO_OSC
obs_t-19_NO_OSC
obs_t-18_NO_OSC
obs_t-17_NO_OSC
obs_t-16_NO_OSC
obs_t-15_NO_OSC
obs_t-14_NO_OSC
obs_t-13_NO_OSC
obs_t-12_NO_OSC
obs_t-11_NO_OSC
obs_t-10_NO_OSC
obs_t-9_NO_OSC
obs_t-8_NO_OSC
obs_t-7_NO_OSC
obs_t-6_NO_OSC
obs_t-5_NO_OSC
obs_t-4_NO_OSC
obs_t-3_NO_OSC
obs_t-2_NO_OSC
obs_t-1_NO_OSC
tide_py_t-24_NO_OSC
tide_py_t-23_NO_OSC
tide_py_t-22_NO_OSC
tide_py_t-21_NO_OSC
tide_py_t-20_NO_OSC
tide_py_t-19_NO_OSC
tide_py_t-18_NO_OSC
tide_py_t-17_NO_OSC
tide_py_t-16_NO_OSC
tide_py_t-15_NO_OSC
tide_py_t-14_NO_OSC
tide_py_t-13_NO_OSC
tide_py_t-12_NO_OSC
tide_py_t-11_NO_OSC
tide_py_t-10_NO_OSC
tide_py_t-9_NO_OSC
tide_py_t-8_NO_OSC
tide_py_t-7_NO_OSC
tide_py_t-6_NO_OSC
tide_py_t-5_NO_OSC
tide_py_t-4_NO_OSC
tide_py_t-3_NO_OSC
tide_py_t-2_NO_OSC
tide_py_t-1_NO_OSC
obs_t-24_NO_TRG
obs_t-23_NO_TRG
obs_t-22_NO_TRG
obs_t-21_NO_TRG
obs_t-20_NO_TRG
obs_t-19_NO_TRG
obs_t-18_NO_TRG
obs_t-17_NO_TRG
obs_t-16_NO_TRG
obs_t-15_NO_TRG
obs_t-14_NO_TRG
obs_t-13_NO_TRG
obs_t-12_NO_TRG
obs_t-11_NO_TRG
obs_t-10_NO_TRG
obs_t-9_NO_TRG
obs_t-8_NO_TRG
obs_t-7_NO_TRG
obs_t-6_NO_TRG
obs_t-5_NO_TRG
obs_t-4_NO_TRG
obs_t-3_NO_TRG
obs_t-2_NO_TRG
obs_t-1_NO_TRG
tide_py_t-24_NO_TRG
tide_py_t-23_NO_TRG
tide_py_t-22_NO_TRG
tide_py_t-21_NO_TRG
tide_py_t-20_NO_TRG
tide_py_t-19_NO_TRG
tide_py_t-18_NO_TRG
tide_py_t-17_NO_TRG
tide_py_t-16_NO_TRG
tide_py_t-15_NO_TRG
tide_py_t-14_NO_TRG
tide_py_t-13_NO_TRG
tide_py_t-12_NO_TRG
tide_py_t-11_NO_TRG
tide_py_t-10_NO_TRG
tide_py_t-9_NO_TRG
tide_py_t-8_NO_TRG
tide_py_t-7_NO_TRG
tide_py_t-6_NO_TRG
tide_py_t-5_NO_TRG
tide_py_t-4_NO_TRG
tide_py_t-3_NO_TRG
tide_py_t-2_NO_TRG
tide_py_t-1_NO_TRG
obs_t-24_NO_AES
obs_t-23_NO_AES
obs_t-22_NO_AES
obs_t-21_NO_AES
obs_t-20_NO_AES
obs_t-19_NO_AES
obs_t-18_NO_AES
obs_t-17_NO_AES
obs_t-16_NO_AES
obs_t-15_NO_AES
obs_t-14_NO_AES
obs_t-13_NO_AES
obs_t-12_NO_AES
obs_t-11_NO_AES
obs_t-10_NO_AES
obs_t-9_NO_AES
obs_t-8_NO_AES
obs_t-7_NO_AES
obs_t-6_NO_AES
obs_t-5_NO_AES
obs_t-4_NO_AES
obs_t-3_NO_AES
obs_t-2_NO_AES
obs_t-1_NO_AES
tide_py_t-24_NO_AES
tide_py_t-23_NO_AES
tide_py_t-22_NO_AES
tide_py_t-21_NO_AES
tide_py_t-20_NO_AES
tide_py_t-19_NO_AES
tide_py_t-18_NO_AES
tide_py_t-17_NO_AES
tide_py_t-16_NO_AES
tide_py_t-15_NO_AES
tide_py_t-14_NO_AES
tide_py_t-13_NO_AES
tide_py_t-12_NO_AES
tide_py_t-11_NO_AES
tide_py_t-10_NO_AES
tide_py_t-9_NO_AES
tide_py_t-8_NO_AES
tide_py_t-7_NO_AES
tide_py_t-6_NO_AES
tide_py_t-5_NO_AES
tide_py_t-4_NO_AES
tide_py_t-3_NO_AES
tide_py_t-2_NO_AES
tide_py_t-1_NO_AES
obs_NO_BGO
obs_t1_NO_BGO
obs_t2_NO_BGO
obs_t3_NO_BGO
obs_t4_NO_BGO
obs_t5_NO_BGO
obs_t6_NO_BGO
obs_t7_NO_BGO
obs_t8_NO_BGO
obs_t9_NO_BGO
obs_t10_NO_BGO
obs_t11_NO_BGO
obs_t12_NO_BGO
obs_t13_NO_BGO
obs_t14_NO_BGO
obs_t15_NO_BGO
obs_t16_NO_BGO
obs_t17_NO_BGO
obs_t18_NO_BGO
obs_t19_NO_BGO
obs_t20_NO_BGO
obs_t21_NO_BGO
obs_t22_NO_BGO
obs_t23_NO_BGO
obs_t24_NO_BGO
obs_t25_NO_BGO
obs_t26_NO_BGO
obs_t27_NO_BGO
obs_t28_NO_BGO
obs_t29_NO_BGO
obs_t30_NO_BGO
obs_t31_NO_BGO
obs_t32_NO_BGO
obs_t33_NO_BGO
obs_t34_NO_BGO
obs_t35_NO_BGO
obs_t36_NO_BGO
obs_t37_NO_BGO
obs_t38_NO_BGO
obs_t39_NO_BGO
obs_t40_NO_BGO
obs_t41_NO_BGO
obs_t42_NO_BGO
obs_t43_NO_BGO
obs_t44_NO_BGO
obs_t45_NO_BGO
obs_t46_NO_BGO
obs_t47_NO_BGO
obs_t48_NO_BGO
obs_t49_NO_BGO
obs_t50_NO_BGO
obs_t51_NO_BGO
obs_t52_NO_BGO
obs_t53_NO_BGO
obs_t54_NO_BGO
obs_t55_NO_BGO
obs_t56_NO_BGO
obs_t57_NO_BGO
obs_t58_NO_BGO
obs_t59_NO_BGO
obs_t60_NO_BGO
tide_py_NO_BGO
tide_py_t1_NO_BGO
tide_py_t2_NO_BGO
tide_py_t3_NO_BGO
tide_py_t4_NO_BGO
tide_py_t5_NO_BGO
tide_py_t6_NO_BGO
tide_py_t7_NO_BGO
tide_py_t8_NO_BGO
tide_py_t9_NO_BGO
tide_py_t10_NO_BGO
tide_py_t11_NO_BGO
tide_py_t12_NO_BGO
tide_py_t13_NO_BGO
tide_py_t14_NO_BGO
tide_py_t15_NO_BGO
tide_py_t16_NO_BGO
tide_py_t17_NO_BGO
tide_py_t18_NO_BGO
tide_py_t19_NO_BGO
tide_py_t20_NO_BGO
tide_py_t21_NO_BGO
tide_py_t22_NO_BGO
tide_py_t23_NO_BGO
tide_py_t24_NO_BGO
tide_py_t25_NO_BGO
tide_py_t26_NO_BGO
tide_py_t27_NO_BGO
tide_py_t28_NO_BGO
tide_py_t29_NO_BGO
tide_py_t30_NO_BGO
tide_py_t31_NO_BGO
tide_py_t32_NO_BGO
tide_py_t33_NO_BGO
tide_py_t34_NO_BGO
tide_py_t35_NO_BGO
tide_py_t36_NO_BGO
tide_py_t37_NO_BGO
tide_py_t38_NO_BGO
tide_py_t39_NO_BGO
tide_py_t40_NO_BGO
tide_py_t41_NO_BGO
tide_py_t42_NO_BGO
tide_py_t43_NO_BGO
tide_py_t44_NO_BGO
tide_py_t45_NO_BGO
tide_py_t46_NO_BGO
tide_py_t47_NO_BGO
tide_py_t48_NO_BGO
tide_py_t49_NO_BGO
tide_py_t50_NO_BGO
tide_py_t51_NO_BGO
tide_py_t52_NO_BGO
tide_py_t53_NO_BGO
tide_py_t54_NO_BGO
tide_py_t55_NO_BGO
tide_py_t56_NO_BGO
tide_py_t57_NO_BGO
tide_py_t58_NO_BGO
tide_py_t59_NO_BGO
tide_py_t60_NO_BGO
obs_NO_VIK
obs_t1_NO_VIK
obs_t2_NO_VIK
obs_t3_NO_VIK
obs_t4_NO_VIK
obs_t5_NO_VIK
obs_t6_NO_VIK
obs_t7_NO_VIK
obs_t8_NO_VIK
obs_t9_NO_VIK
obs_t10_NO_VIK
obs_t11_NO_VIK
obs_t12_NO_VIK
obs_t13_NO_VIK
obs_t14_NO_VIK
obs_t15_NO_VIK
obs_t16_NO_VIK
obs_t17_NO_VIK
obs_t18_NO_VIK
obs_t19_NO_VIK
obs_t20_NO_VIK
obs_t21_NO_VIK
obs_t22_NO_VIK
obs_t23_NO_VIK
obs_t24_NO_VIK
obs_t25_NO_VIK
obs_t26_NO_VIK
obs_t27_NO_VIK
obs_t28_NO_VIK
obs_t29_NO_VIK
obs_t30_NO_VIK
obs_t31_NO_VIK
obs_t32_NO_VIK
obs_t33_NO_VIK
obs_t34_NO_VIK
obs_t35_NO_VIK
obs_t36_NO_VIK
obs_t37_NO_VIK
obs_t38_NO_VIK
obs_t39_NO_VIK
obs_t40_NO_VIK
obs_t41_NO_VIK
obs_t42_NO_VIK
obs_t43_NO_VIK
obs_t44_NO_VIK
obs_t45_NO_VIK
obs_t46_NO_VIK
obs_t47_NO_VIK
obs_t48_NO_VIK
obs_t49_NO_VIK
obs_t50_NO_VIK
obs_t51_NO_VIK
obs_t52_NO_VIK
obs_t53_NO_VIK
obs_t54_NO_VIK
obs_t55_NO_VIK
obs_t56_NO_VIK
obs_t57_NO_VIK
obs_t58_NO_VIK
obs_t59_NO_VIK
obs_t60_NO_VIK
tide_py_NO_VIK
tide_py_t1_NO_VIK
tide_py_t2_NO_VIK
tide_py_t3_NO_VIK
tide_py_t4_NO_VIK
tide_py_t5_NO_VIK
tide_py_t6_NO_VIK
tide_py_t7_NO_VIK
tide_py_t8_NO_VIK
tide_py_t9_NO_VIK
tide_py_t10_NO_VIK
tide_py_t11_NO_VIK
tide_py_t12_NO_VIK
tide_py_t13_NO_VIK
tide_py_t14_NO_VIK
tide_py_t15_NO_VIK
tide_py_t16_NO_VIK
tide_py_t17_NO_VIK
tide_py_t18_NO_VIK
tide_py_t19_NO_VIK
tide_py_t20_NO_VIK
tide_py_t21_NO_VIK
tide_py_t22_NO_VIK
tide_py_t23_NO_VIK
tide_py_t24_NO_VIK
tide_py_t25_NO_VIK
tide_py_t26_NO_VIK
tide_py_t27_NO_VIK
tide_py_t28_NO_VIK
tide_py_t29_NO_VIK
tide_py_t30_NO_VIK
tide_py_t31_NO_VIK
tide_py_t32_NO_VIK
tide_py_t33_NO_VIK
tide_py_t34_NO_VIK
tide_py_t35_NO_VIK
tide_py_t36_NO_VIK
tide_py_t37_NO_VIK
tide_py_t38_NO_VIK
tide_py_t39_NO_VIK
tide_py_t40_NO_VIK
tide_py_t41_NO_VIK
tide_py_t42_NO_VIK
tide_py_t43_NO_VIK
tide_py_t44_NO_VIK
tide_py_t45_NO_VIK
tide_py_t46_NO_VIK
tide_py_t47_NO_VIK
tide_py_t48_NO_VIK
tide_py_t49_NO_VIK
tide_py_t50_NO_VIK
tide_py_t51_NO_VIK
tide_py_t52_NO_VIK
tide_py_t53_NO_VIK
tide_py_t54_NO_VIK
tide_py_t55_NO_VIK
tide_py_t56_NO_VIK
tide_py_t57_NO_VIK
tide_py_t58_NO_VIK
tide_py_t59_NO_VIK
tide_py_t60_NO_VIK
obs_NO_OSC
obs_t1_NO_OSC
obs_t2_NO_OSC
obs_t3_NO_OSC
obs_t4_NO_OSC
obs_t5_NO_OSC
obs_t6_NO_OSC
obs_t7_NO_OSC
obs_t8_NO_OSC
obs_t9_NO_OSC
obs_t10_NO_OSC
obs_t11_NO_OSC
obs_t12_NO_OSC
obs_t13_NO_OSC
obs_t14_NO_OSC
obs_t15_NO_OSC
obs_t16_NO_OSC
obs_t17_NO_OSC
obs_t18_NO_OSC
obs_t19_NO_OSC
obs_t20_NO_OSC
obs_t21_NO_OSC
obs_t22_NO_OSC
obs_t23_NO_OSC
obs_t24_NO_OSC
obs_t25_NO_OSC
obs_t26_NO_OSC
obs_t27_NO_OSC
obs_t28_NO_OSC
obs_t29_NO_OSC
obs_t30_NO_OSC
obs_t31_NO_OSC
obs_t32_NO_OSC
obs_t33_NO_OSC
obs_t34_NO_OSC
obs_t35_NO_OSC
obs_t36_NO_OSC
obs_t37_NO_OSC
obs_t38_NO_OSC
obs_t39_NO_OSC
obs_t40_NO_OSC
obs_t41_NO_OSC
obs_t42_NO_OSC
obs_t43_NO_OSC
obs_t44_NO_OSC
obs_t45_NO_OSC
obs_t46_NO_OSC
obs_t47_NO_OSC
obs_t48_NO_OSC
obs_t49_NO_OSC
obs_t50_NO_OSC
obs_t51_NO_OSC
obs_t52_NO_OSC
obs_t53_NO_OSC
obs_t54_NO_OSC
obs_t55_NO_OSC
obs_t56_NO_OSC
obs_t57_NO_OSC
obs_t58_NO_OSC
obs_t59_NO_OSC
obs_t60_NO_OSC
tide_py_NO_OSC
tide_py_t1_NO_OSC
tide_py_t2_NO_OSC
tide_py_t3_NO_OSC
tide_py_t4_NO_OSC
tide_py_t5_NO_OSC
tide_py_t6_NO_OSC
tide_py_t7_NO_OSC
tide_py_t8_NO_OSC
tide_py_t9_NO_OSC
tide_py_t10_NO_OSC
tide_py_t11_NO_OSC
tide_py_t12_NO_OSC
tide_py_t13_NO_OSC
tide_py_t14_NO_OSC
tide_py_t15_NO_OSC
tide_py_t16_NO_OSC
tide_py_t17_NO_OSC
tide_py_t18_NO_OSC
tide_py_t19_NO_OSC
tide_py_t20_NO_OSC
tide_py_t21_NO_OSC
tide_py_t22_NO_OSC
tide_py_t23_NO_OSC
tide_py_t24_NO_OSC
tide_py_t25_NO_OSC
tide_py_t26_NO_OSC
tide_py_t27_NO_OSC
tide_py_t28_NO_OSC
tide_py_t29_NO_OSC
tide_py_t30_NO_OSC
tide_py_t31_NO_OSC
tide_py_t32_NO_OSC
tide_py_t33_NO_OSC
tide_py_t34_NO_OSC
tide_py_t35_NO_OSC
tide_py_t36_NO_OSC
tide_py_t37_NO_OSC
tide_py_t38_NO_OSC
tide_py_t39_NO_OSC
tide_py_t40_NO_OSC
tide_py_t41_NO_OSC
tide_py_t42_NO_OSC
tide_py_t43_NO_OSC
tide_py_t44_NO_OSC
tide_py_t45_NO_OSC
tide_py_t46_NO_OSC
tide_py_t47_NO_OSC
tide_py_t48_NO_OSC
tide_py_t49_NO_OSC
tide_py_t50_NO_OSC
tide_py_t51_NO_OSC
tide_py_t52_NO_OSC
tide_py_t53_NO_OSC
tide_py_t54_NO_OSC
tide_py_t55_NO_OSC
tide_py_t56_NO_OSC
tide_py_t57_NO_OSC
tide_py_t58_NO_OSC
tide_py_t59_NO_OSC
tide_py_t60_NO_OSC
obs_NO_TRG
obs_t1_NO_TRG
obs_t2_NO_TRG
obs_t3_NO_TRG
obs_t4_NO_TRG
obs_t5_NO_TRG
obs_t6_NO_TRG
obs_t7_NO_TRG
obs_t8_NO_TRG
obs_t9_NO_TRG
obs_t10_NO_TRG
obs_t11_NO_TRG
obs_t12_NO_TRG
obs_t13_NO_TRG
obs_t14_NO_TRG
obs_t15_NO_TRG
obs_t16_NO_TRG
obs_t17_NO_TRG
obs_t18_NO_TRG
obs_t19_NO_TRG
obs_t20_NO_TRG
obs_t21_NO_TRG
obs_t22_NO_TRG
obs_t23_NO_TRG
obs_t24_NO_TRG
obs_t25_NO_TRG
obs_t26_NO_TRG
obs_t27_NO_TRG
obs_t28_NO_TRG
obs_t29_NO_TRG
obs_t30_NO_TRG
obs_t31_NO_TRG
obs_t32_NO_TRG
obs_t33_NO_TRG
obs_t34_NO_TRG
obs_t35_NO_TRG
obs_t36_NO_TRG
obs_t37_NO_TRG
obs_t38_NO_TRG
obs_t39_NO_TRG
obs_t40_NO_TRG
obs_t41_NO_TRG
obs_t42_NO_TRG
obs_t43_NO_TRG
obs_t44_NO_TRG
obs_t45_NO_TRG
obs_t46_NO_TRG
obs_t47_NO_TRG
obs_t48_NO_TRG
obs_t49_NO_TRG
obs_t50_NO_TRG
obs_t51_NO_TRG
obs_t52_NO_TRG
obs_t53_NO_TRG
obs_t54_NO_TRG
obs_t55_NO_TRG
obs_t56_NO_TRG
obs_t57_NO_TRG
obs_t58_NO_TRG
obs_t59_NO_TRG
obs_t60_NO_TRG
tide_py_NO_TRG
tide_py_t1_NO_TRG
tide_py_t2_NO_TRG
tide_py_t3_NO_TRG
tide_py_t4_NO_TRG
tide_py_t5_NO_TRG
tide_py_t6_NO_TRG
tide_py_t7_NO_TRG
tide_py_t8_NO_TRG
tide_py_t9_NO_TRG
tide_py_t10_NO_TRG
tide_py_t11_NO_TRG
tide_py_t12_NO_TRG
tide_py_t13_NO_TRG
tide_py_t14_NO_TRG
tide_py_t15_NO_TRG
tide_py_t16_NO_TRG
tide_py_t17_NO_TRG
tide_py_t18_NO_TRG
tide_py_t19_NO_TRG
tide_py_t20_NO_TRG
tide_py_t21_NO_TRG
tide_py_t22_NO_TRG
tide_py_t23_NO_TRG
tide_py_t24_NO_TRG
tide_py_t25_NO_TRG
tide_py_t26_NO_TRG
tide_py_t27_NO_TRG
tide_py_t28_NO_TRG
tide_py_t29_NO_TRG
tide_py_t30_NO_TRG
tide_py_t31_NO_TRG
tide_py_t32_NO_TRG
tide_py_t33_NO_TRG
tide_py_t34_NO_TRG
tide_py_t35_NO_TRG
tide_py_t36_NO_TRG
tide_py_t37_NO_TRG
tide_py_t38_NO_TRG
tide_py_t39_NO_TRG
tide_py_t40_NO_TRG
tide_py_t41_NO_TRG
tide_py_t42_NO_TRG
tide_py_t43_NO_TRG
tide_py_t44_NO_TRG
tide_py_t45_NO_TRG
tide_py_t46_NO_TRG
tide_py_t47_NO_TRG
tide_py_t48_NO_TRG
tide_py_t49_NO_TRG
tide_py_t50_NO_TRG
tide_py_t51_NO_TRG
tide_py_t52_NO_TRG
tide_py_t53_NO_TRG
tide_py_t54_NO_TRG
tide_py_t55_NO_TRG
tide_py_t56_NO_TRG
tide_py_t57_NO_TRG
tide_py_t58_NO_TRG
tide_py_t59_NO_TRG
tide_py_t60_NO_TRG
obs_NO_AES
obs_t1_NO_AES
obs_t2_NO_AES
obs_t3_NO_AES
obs_t4_NO_AES
obs_t5_NO_AES
obs_t6_NO_AES
obs_t7_NO_AES
obs_t8_NO_AES
obs_t9_NO_AES
obs_t10_NO_AES
obs_t11_NO_AES
obs_t12_NO_AES
obs_t13_NO_AES
obs_t14_NO_AES
obs_t15_NO_AES
obs_t16_NO_AES
obs_t17_NO_AES
obs_t18_NO_AES
obs_t19_NO_AES
obs_t20_NO_AES
obs_t21_NO_AES
obs_t22_NO_AES
obs_t23_NO_AES
obs_t24_NO_AES
obs_t25_NO_AES
obs_t26_NO_AES
obs_t27_NO_AES
obs_t28_NO_AES
obs_t29_NO_AES
obs_t30_NO_AES
obs_t31_NO_AES
obs_t32_NO_AES
obs_t33_NO_AES
obs_t34_NO_AES
obs_t35_NO_AES
obs_t36_NO_AES
obs_t37_NO_AES
obs_t38_NO_AES
obs_t39_NO_AES
obs_t40_NO_AES
obs_t41_NO_AES
obs_t42_NO_AES
obs_t43_NO_AES
obs_t44_NO_AES
obs_t45_NO_AES
obs_t46_NO_AES
obs_t47_NO_AES
obs_t48_NO_AES
obs_t49_NO_AES
obs_t50_NO_AES
obs_t51_NO_AES
obs_t52_NO_AES
obs_t53_NO_AES
obs_t54_NO_AES
obs_t55_NO_AES
obs_t56_NO_AES
obs_t57_NO_AES
obs_t58_NO_AES
obs_t59_NO_AES
obs_t60_NO_AES
tide_py_NO_AES
tide_py_t1_NO_AES
tide_py_t2_NO_AES
tide_py_t3_NO_AES
tide_py_t4_NO_AES
tide_py_t5_NO_AES
tide_py_t6_NO_AES
tide_py_t7_NO_AES
tide_py_t8_NO_AES
tide_py_t9_NO_AES
tide_py_t10_NO_AES
tide_py_t11_NO_AES
tide_py_t12_NO_AES
tide_py_t13_NO_AES
tide_py_t14_NO_AES
tide_py_t15_NO_AES
tide_py_t16_NO_AES
tide_py_t17_NO_AES
tide_py_t18_NO_AES
tide_py_t19_NO_AES
tide_py_t20_NO_AES
tide_py_t21_NO_AES
tide_py_t22_NO_AES
tide_py_t23_NO_AES
tide_py_t24_NO_AES
tide_py_t25_NO_AES
tide_py_t26_NO_AES
tide_py_t27_NO_AES
tide_py_t28_NO_AES
tide_py_t29_NO_AES
tide_py_t30_NO_AES
tide_py_t31_NO_AES
tide_py_t32_NO_AES
tide_py_t33_NO_AES
tide_py_t34_NO_AES
tide_py_t35_NO_AES
tide_py_t36_NO_AES
tide_py_t37_NO_AES
tide_py_t38_NO_AES
tide_py_t39_NO_AES
tide_py_t40_NO_AES
tide_py_t41_NO_AES
tide_py_t42_NO_AES
tide_py_t43_NO_AES
tide_py_t44_NO_AES
tide_py_t45_NO_AES
tide_py_t46_NO_AES
tide_py_t47_NO_AES
tide_py_t48_NO_AES
tide_py_t49_NO_AES
tide_py_t50_NO_AES
tide_py_t51_NO_AES
tide_py_t52_NO_AES
tide_py_t53_NO_AES
tide_py_t54_NO_AES
tide_py_t55_NO_AES
tide_py_t56_NO_AES
tide_py_t57_NO_AES
tide_py_t58_NO_AES
tide_py_t59_NO_AES
tide_py_t60_NO_AES
v10_NO_BGO
v10_t1_NO_BGO
v10_t2_NO_BGO
v10_t3_NO_BGO
v10_t4_NO_BGO
v10_t5_NO_BGO
v10_t6_NO_BGO
v10_t7_NO_BGO
v10_t8_NO_BGO
v10_t9_NO_BGO
v10_t10_NO_BGO
v10_t11_NO_BGO
v10_t12_NO_BGO
v10_t13_NO_BGO
v10_t14_NO_BGO
v10_t15_NO_BGO
v10_t16_NO_BGO
v10_t17_NO_BGO
v10_t18_NO_BGO
v10_t19_NO_BGO
v10_t20_NO_BGO
v10_t21_NO_BGO
v10_t22_NO_BGO
v10_t23_NO_BGO
v10_t24_NO_BGO
v10_t25_NO_BGO
v10_t26_NO_BGO
v10_t27_NO_BGO
v10_t28_NO_BGO
v10_t29_NO_BGO
v10_t30_NO_BGO
v10_t31_NO_BGO
v10_t32_NO_BGO
v10_t33_NO_BGO
v10_t34_NO_BGO
v10_t35_NO_BGO
v10_t36_NO_BGO
v10_t37_NO_BGO
v10_t38_NO_BGO
v10_t39_NO_BGO
v10_t40_NO_BGO
v10_t41_NO_BGO
v10_t42_NO_BGO
v10_t43_NO_BGO
v10_t44_NO_BGO
v10_t45_NO_BGO
v10_t46_NO_BGO
v10_t47_NO_BGO
v10_t48_NO_BGO
v10_t49_NO_BGO
v10_t50_NO_BGO
v10_t51_NO_BGO
v10_t52_NO_BGO
v10_t53_NO_BGO
v10_t54_NO_BGO
v10_t55_NO_BGO
v10_t56_NO_BGO
v10_t57_NO_BGO
v10_t58_NO_BGO
v10_t59_NO_BGO
v10_t60_NO_BGO
u10_NO_BGO
u10_t1_NO_BGO
u10_t2_NO_BGO
u10_t3_NO_BGO
u10_t4_NO_BGO
u10_t5_NO_BGO
u10_t6_NO_BGO
u10_t7_NO_BGO
u10_t8_NO_BGO
u10_t9_NO_BGO
u10_t10_NO_BGO
u10_t11_NO_BGO
u10_t12_NO_BGO
u10_t13_NO_BGO
u10_t14_NO_BGO
u10_t15_NO_BGO
u10_t16_NO_BGO
u10_t17_NO_BGO
u10_t18_NO_BGO
u10_t19_NO_BGO
u10_t20_NO_BGO
u10_t21_NO_BGO
u10_t22_NO_BGO
u10_t23_NO_BGO
u10_t24_NO_BGO
u10_t25_NO_BGO
u10_t26_NO_BGO
u10_t27_NO_BGO
u10_t28_NO_BGO
u10_t29_NO_BGO
u10_t30_NO_BGO
u10_t31_NO_BGO
u10_t32_NO_BGO
u10_t33_NO_BGO
u10_t34_NO_BGO
u10_t35_NO_BGO
u10_t36_NO_BGO
u10_t37_NO_BGO
u10_t38_NO_BGO
u10_t39_NO_BGO
u10_t40_NO_BGO
u10_t41_NO_BGO
u10_t42_NO_BGO
u10_t43_NO_BGO
u10_t44_NO_BGO
u10_t45_NO_BGO
u10_t46_NO_BGO
u10_t47_NO_BGO
u10_t48_NO_BGO
u10_t49_NO_BGO
u10_t50_NO_BGO
u10_t51_NO_BGO
u10_t52_NO_BGO
u10_t53_NO_BGO
u10_t54_NO_BGO
u10_t55_NO_BGO
u10_t56_NO_BGO
u10_t57_NO_BGO
u10_t58_NO_BGO
u10_t59_NO_BGO
u10_t60_NO_BGO
v10_NO_VIK
v10_t1_NO_VIK
v10_t2_NO_VIK
v10_t3_NO_VIK
v10_t4_NO_VIK
v10_t5_NO_VIK
v10_t6_NO_VIK
v10_t7_NO_VIK
v10_t8_NO_VIK
v10_t9_NO_VIK
v10_t10_NO_VIK
v10_t11_NO_VIK
v10_t12_NO_VIK
v10_t13_NO_VIK
v10_t14_NO_VIK
v10_t15_NO_VIK
v10_t16_NO_VIK
v10_t17_NO_VIK
v10_t18_NO_VIK
v10_t19_NO_VIK
v10_t20_NO_VIK
v10_t21_NO_VIK
v10_t22_NO_VIK
v10_t23_NO_VIK
v10_t24_NO_VIK
v10_t25_NO_VIK
v10_t26_NO_VIK
v10_t27_NO_VIK
v10_t28_NO_VIK
v10_t29_NO_VIK
v10_t30_NO_VIK
v10_t31_NO_VIK
v10_t32_NO_VIK
v10_t33_NO_VIK
v10_t34_NO_VIK
v10_t35_NO_VIK
v10_t36_NO_VIK
v10_t37_NO_VIK
v10_t38_NO_VIK
v10_t39_NO_VIK
v10_t40_NO_VIK
v10_t41_NO_VIK
v10_t42_NO_VIK
v10_t43_NO_VIK
v10_t44_NO_VIK
v10_t45_NO_VIK
v10_t46_NO_VIK
v10_t47_NO_VIK
v10_t48_NO_VIK
v10_t49_NO_VIK
v10_t50_NO_VIK
v10_t51_NO_VIK
v10_t52_NO_VIK
v10_t53_NO_VIK
v10_t54_NO_VIK
v10_t55_NO_VIK
v10_t56_NO_VIK
v10_t57_NO_VIK
v10_t58_NO_VIK
v10_t59_NO_VIK
v10_t60_NO_VIK
u10_NO_VIK
u10_t1_NO_VIK
u10_t2_NO_VIK
u10_t3_NO_VIK
u10_t4_NO_VIK
u10_t5_NO_VIK
u10_t6_NO_VIK
u10_t7_NO_VIK
u10_t8_NO_VIK
u10_t9_NO_VIK
u10_t10_NO_VIK
u10_t11_NO_VIK
u10_t12_NO_VIK
u10_t13_NO_VIK
u10_t14_NO_VIK
u10_t15_NO_VIK
u10_t16_NO_VIK
u10_t17_NO_VIK
u10_t18_NO_VIK
u10_t19_NO_VIK
u10_t20_NO_VIK
u10_t21_NO_VIK
u10_t22_NO_VIK
u10_t23_NO_VIK
u10_t24_NO_VIK
u10_t25_NO_VIK
u10_t26_NO_VIK
u10_t27_NO_VIK
u10_t28_NO_VIK
u10_t29_NO_VIK
u10_t30_NO_VIK
u10_t31_NO_VIK
u10_t32_NO_VIK
u10_t33_NO_VIK
u10_t34_NO_VIK
u10_t35_NO_VIK
u10_t36_NO_VIK
u10_t37_NO_VIK
u10_t38_NO_VIK
u10_t39_NO_VIK
u10_t40_NO_VIK
u10_t41_NO_VIK
u10_t42_NO_VIK
u10_t43_NO_VIK
u10_t44_NO_VIK
u10_t45_NO_VIK
u10_t46_NO_VIK
u10_t47_NO_VIK
u10_t48_NO_VIK
u10_t49_NO_VIK
u10_t50_NO_VIK
u10_t51_NO_VIK
u10_t52_NO_VIK
u10_t53_NO_VIK
u10_t54_NO_VIK
u10_t55_NO_VIK
u10_t56_NO_VIK
u10_t57_NO_VIK
u10_t58_NO_VIK
u10_t59_NO_VIK
u10_t60_NO_VIK
v10_NO_OSC
v10_t1_NO_OSC
v10_t2_NO_OSC
v10_t3_NO_OSC
v10_t4_NO_OSC
v10_t5_NO_OSC
v10_t6_NO_OSC
v10_t7_NO_OSC
v10_t8_NO_OSC
v10_t9_NO_OSC
v10_t10_NO_OSC
v10_t11_NO_OSC
v10_t12_NO_OSC
v10_t13_NO_OSC
v10_t14_NO_OSC
v10_t15_NO_OSC
v10_t16_NO_OSC
v10_t17_NO_OSC
v10_t18_NO_OSC
v10_t19_NO_OSC
v10_t20_NO_OSC
v10_t21_NO_OSC
v10_t22_NO_OSC
v10_t23_NO_OSC
v10_t24_NO_OSC
v10_t25_NO_OSC
v10_t26_NO_OSC
v10_t27_NO_OSC
v10_t28_NO_OSC
v10_t29_NO_OSC
v10_t30_NO_OSC
v10_t31_NO_OSC
v10_t32_NO_OSC
v10_t33_NO_OSC
v10_t34_NO_OSC
v10_t35_NO_OSC
v10_t36_NO_OSC
v10_t37_NO_OSC
v10_t38_NO_OSC
v10_t39_NO_OSC
v10_t40_NO_OSC
v10_t41_NO_OSC
v10_t42_NO_OSC
v10_t43_NO_OSC
v10_t44_NO_OSC
v10_t45_NO_OSC
v10_t46_NO_OSC
v10_t47_NO_OSC
v10_t48_NO_OSC
v10_t49_NO_OSC
v10_t50_NO_OSC
v10_t51_NO_OSC
v10_t52_NO_OSC
v10_t53_NO_OSC
v10_t54_NO_OSC
v10_t55_NO_OSC
v10_t56_NO_OSC
v10_t57_NO_OSC
v10_t58_NO_OSC
v10_t59_NO_OSC
v10_t60_NO_OSC
u10_NO_OSC
u10_t1_NO_OSC
u10_t2_NO_OSC
u10_t3_NO_OSC
u10_t4_NO_OSC
u10_t5_NO_OSC
u10_t6_NO_OSC
u10_t7_NO_OSC
u10_t8_NO_OSC
u10_t9_NO_OSC
u10_t10_NO_OSC
u10_t11_NO_OSC
u10_t12_NO_OSC
u10_t13_NO_OSC
u10_t14_NO_OSC
u10_t15_NO_OSC
u10_t16_NO_OSC
u10_t17_NO_OSC
u10_t18_NO_OSC
u10_t19_NO_OSC
u10_t20_NO_OSC
u10_t21_NO_OSC
u10_t22_NO_OSC
u10_t23_NO_OSC
u10_t24_NO_OSC
u10_t25_NO_OSC
u10_t26_NO_OSC
u10_t27_NO_OSC
u10_t28_NO_OSC
u10_t29_NO_OSC
u10_t30_NO_OSC
u10_t31_NO_OSC
u10_t32_NO_OSC
u10_t33_NO_OSC
u10_t34_NO_OSC
u10_t35_NO_OSC
u10_t36_NO_OSC
u10_t37_NO_OSC
u10_t38_NO_OSC
u10_t39_NO_OSC
u10_t40_NO_OSC
u10_t41_NO_OSC
u10_t42_NO_OSC
u10_t43_NO_OSC
u10_t44_NO_OSC
u10_t45_NO_OSC
u10_t46_NO_OSC
u10_t47_NO_OSC
u10_t48_NO_OSC
u10_t49_NO_OSC
u10_t50_NO_OSC
u10_t51_NO_OSC
u10_t52_NO_OSC
u10_t53_NO_OSC
u10_t54_NO_OSC
u10_t55_NO_OSC
u10_t56_NO_OSC
u10_t57_NO_OSC
u10_t58_NO_OSC
u10_t59_NO_OSC
u10_t60_NO_OSC
v10_NO_TRG
v10_t1_NO_TRG
v10_t2_NO_TRG
v10_t3_NO_TRG
v10_t4_NO_TRG
v10_t5_NO_TRG
v10_t6_NO_TRG
v10_t7_NO_TRG

# Ope files directly to check if there are actually NaNs in the data

In [19]:
import xarray as xr

In [20]:
data_dir = '/lustre/storeB/project/metproduction/products/util/vannstand/'
f = data_dir + 'kyststasjoner_norge.nc2025051900'

In [21]:
data = xr.open_dataset(f)
data

<xarray.Dataset>
Dimensions:                       (time: 721, ensemble_member: 52, dummy: 1,
                                   station: 32, station_strlen: 80)
Coordinates:
  * time                          (time) datetime64[ns] 2025-05-18T12:00:00 ....
  * station                       (station) int32 0 1 2 3 4 5 ... 27 28 29 30 31
  * dummy                         (dummy) int32 -2147483647
  * ensemble_member               (ensemble_member) float32 9.969e+36 ... 9.9...
Dimensions without coordinates: station_strlen
Data variables: (12/22)
    stormsurge                    (time, ensemble_member, dummy, station) float32 ...
    bias                          (station) float32 ...
    stormsurge_corrected          (time, ensemble_member, dummy, station) float32 ...
    totalwater                    (time, ensemble_member, dummy, station) float32 ...
    totalwater_at_chartdatum      (time, ensemble_member, dummy, station) float32 ...
    tide                          (time, dummy, station) float32 ...
    ...                            ...
    krit2                         (station) float32 ...
    krit3                         (station) float32 ...
    null_offset                   (station) float32 ...
    prob1                         (time, station) float32 ...
    prob2                         (time, station) float32 ...
    prob3                         (time, station) float32 ...
Attributes:
    About:        EPS Storm surge forecasts generated based on the ROMS ocean...
    Author:       nilsmk
    Conventions:  CF-1.4
    Contact:      vannstand@met.no

In [22]:
# Station nr. 1 is OSC
data.station_name[:, 1].values

array([b'o', b's', b'c', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'',
       b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'',
       b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'',
       b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'',
       b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'',
       b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'', b'',
       b'', b''], dtype='|S1')

In [23]:
data.observed_at_chartdatum[0, 0, 1].values

array(0.42999998, dtype=float32)

In [24]:
# This is the same value as in prepare df
data.stormsurge_corrected[0, -1, 0, 1].values

array(-0.1597505, dtype=float32)

In [25]:
data.bias[1].values

array(0.11488321, dtype=float32)